apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-2
  namespace: test-gitops
spec:
  destination:
    server: 'https://api.ocp2.sandbox97.opentlc.com:6443'
    namespace: test-2
  project: default
  source:
    path: deployment-2/
    repoURL: 'https://github.com/romerobu/test-app-of-apps.git'
    targetRevision: demo-acm
