apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-1
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://api.ocp1.sandbox97.opentlc.com:6443'
    namespace: test-gitops
  project: default
  source:
    path: app-of-apps-destination-1/
    repoURL: 'https://github.com/romerobu/test-app-of-apps.git'
    targetRevision: demo-acm
