apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-2-in-destination
  namespace: test-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: test-2
  project: default
  source:
    path: deployment-2/
    repoURL: 'https://github.com/romerobu/test-app-of-apps.git'
    targetRevision: demo-acm
  syncPolicy:
    syncOptions:
      - CreateNamespace=true